/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by gensrv_cpp from file /home/paschalidoud/pandora_RoCKIn2014/src/object_recognition_msg/src/rec_msg_and_serv/srv/rec.srv
 *
 */


#ifndef REC_MSG_AND_SERV_MESSAGE_REC_H
#define REC_MSG_AND_SERV_MESSAGE_REC_H

#include <ros/service_traits.h>


#include <rec_msg_and_serv/recRequest.h>
#include <rec_msg_and_serv/recResponse.h>


namespace rec_msg_and_serv
{

struct rec
{

typedef recRequest Request;
typedef recResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct rec
} // namespace rec_msg_and_serv


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rec_msg_and_serv::rec > {
  static const char* value()
  {
    return "2c4745a1274bef7c9fa1e4e9500ac492";
  }

  static const char* value(const ::rec_msg_and_serv::rec&) { return value(); }
};

template<>
struct DataType< ::rec_msg_and_serv::rec > {
  static const char* value()
  {
    return "rec_msg_and_serv/rec";
  }

  static const char* value(const ::rec_msg_and_serv::rec&) { return value(); }
};


// service_traits::MD5Sum< ::rec_msg_and_serv::recRequest> should match 
// service_traits::MD5Sum< ::rec_msg_and_serv::rec > 
template<>
struct MD5Sum< ::rec_msg_and_serv::recRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rec_msg_and_serv::rec >::value();
  }
  static const char* value(const ::rec_msg_and_serv::recRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rec_msg_and_serv::recRequest> should match 
// service_traits::DataType< ::rec_msg_and_serv::rec > 
template<>
struct DataType< ::rec_msg_and_serv::recRequest>
{
  static const char* value()
  {
    return DataType< ::rec_msg_and_serv::rec >::value();
  }
  static const char* value(const ::rec_msg_and_serv::recRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rec_msg_and_serv::recResponse> should match 
// service_traits::MD5Sum< ::rec_msg_and_serv::rec > 
template<>
struct MD5Sum< ::rec_msg_and_serv::recResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rec_msg_and_serv::rec >::value();
  }
  static const char* value(const ::rec_msg_and_serv::recResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rec_msg_and_serv::recResponse> should match 
// service_traits::DataType< ::rec_msg_and_serv::rec > 
template<>
struct DataType< ::rec_msg_and_serv::recResponse>
{
  static const char* value()
  {
    return DataType< ::rec_msg_and_serv::rec >::value();
  }
  static const char* value(const ::rec_msg_and_serv::recResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // REC_MSG_AND_SERV_MESSAGE_REC_H
