/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/paschalidoud/pandora_RoCKIn2014/src/object_classification_msg/src/soc_msg_and_serv/srv/segment_and_classify.srv
 *
 */


#ifndef SOC_MSG_AND_SERV_MESSAGE_SEGMENT_AND_CLASSIFYRESPONSE_H
#define SOC_MSG_AND_SERV_MESSAGE_SEGMENT_AND_CLASSIFYRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/String.h>

namespace soc_msg_and_serv
{
template <class ContainerAllocator>
struct segment_and_classifyResponse_
{
  typedef segment_and_classifyResponse_<ContainerAllocator> Type;

  segment_and_classifyResponse_()
    : categories_found()  {
    }
  segment_and_classifyResponse_(const ContainerAllocator& _alloc)
    : categories_found(_alloc)  {
    }



   typedef std::vector< ::std_msgs::String_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::std_msgs::String_<ContainerAllocator> >::other >  _categories_found_type;
  _categories_found_type categories_found;




  typedef boost::shared_ptr< ::soc_msg_and_serv::segment_and_classifyResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::soc_msg_and_serv::segment_and_classifyResponse_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct segment_and_classifyResponse_

typedef ::soc_msg_and_serv::segment_and_classifyResponse_<std::allocator<void> > segment_and_classifyResponse;

typedef boost::shared_ptr< ::soc_msg_and_serv::segment_and_classifyResponse > segment_and_classifyResponsePtr;
typedef boost::shared_ptr< ::soc_msg_and_serv::segment_and_classifyResponse const> segment_and_classifyResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::soc_msg_and_serv::segment_and_classifyResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::soc_msg_and_serv::segment_and_classifyResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace soc_msg_and_serv

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/hydro/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/hydro/share/geometry_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/hydro/share/sensor_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::soc_msg_and_serv::segment_and_classifyResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::soc_msg_and_serv::segment_and_classifyResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::soc_msg_and_serv::segment_and_classifyResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::soc_msg_and_serv::segment_and_classifyResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::soc_msg_and_serv::segment_and_classifyResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::soc_msg_and_serv::segment_and_classifyResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::soc_msg_and_serv::segment_and_classifyResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2e30bd2dbf857aa0f6760754816ef92e";
  }

  static const char* value(const ::soc_msg_and_serv::segment_and_classifyResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2e30bd2dbf857aa0ULL;
  static const uint64_t static_value2 = 0xf6760754816ef92eULL;
};

template<class ContainerAllocator>
struct DataType< ::soc_msg_and_serv::segment_and_classifyResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "soc_msg_and_serv/segment_and_classifyResponse";
  }

  static const char* value(const ::soc_msg_and_serv::segment_and_classifyResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::soc_msg_and_serv::segment_and_classifyResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/String[] categories_found\n\
\n\
================================================================================\n\
MSG: std_msgs/String\n\
string data\n\
";
  }

  static const char* value(const ::soc_msg_and_serv::segment_and_classifyResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::soc_msg_and_serv::segment_and_classifyResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.categories_found);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct segment_and_classifyResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::soc_msg_and_serv::segment_and_classifyResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::soc_msg_and_serv::segment_and_classifyResponse_<ContainerAllocator>& v)
  {
    s << indent << "categories_found[]" << std::endl;
    for (size_t i = 0; i < v.categories_found.size(); ++i)
    {
      s << indent << "  categories_found[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::std_msgs::String_<ContainerAllocator> >::stream(s, indent + "    ", v.categories_found[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SOC_MSG_AND_SERV_MESSAGE_SEGMENT_AND_CLASSIFYRESPONSE_H
