/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/paschalidoud/object_ws/src/object_recognition_msg/src/rec_msg_and_serv/srv/rec.srv
 *
 */


#ifndef REC_MSG_AND_SERV_MESSAGE_RECRESPONSE_H
#define REC_MSG_AND_SERV_MESSAGE_RECRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/String.h>
#include <geometry_msgs/Pose.h>

namespace rec_msg_and_serv
{
template <class ContainerAllocator>
struct recResponse_
{
  typedef recResponse_<ContainerAllocator> Type;

  recResponse_()
    : models_found()
    , confidences_found()
    , poses_found()  {
    }
  recResponse_(const ContainerAllocator& _alloc)
    : models_found(_alloc)
    , confidences_found(_alloc)
    , poses_found(_alloc)  {
    }



   typedef std::vector< ::std_msgs::String_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::std_msgs::String_<ContainerAllocator> >::other >  _models_found_type;
  _models_found_type models_found;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _confidences_found_type;
  _confidences_found_type confidences_found;

   typedef std::vector< ::geometry_msgs::Pose_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Pose_<ContainerAllocator> >::other >  _poses_found_type;
  _poses_found_type poses_found;




  typedef boost::shared_ptr< ::rec_msg_and_serv::recResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rec_msg_and_serv::recResponse_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct recResponse_

typedef ::rec_msg_and_serv::recResponse_<std::allocator<void> > recResponse;

typedef boost::shared_ptr< ::rec_msg_and_serv::recResponse > recResponsePtr;
typedef boost::shared_ptr< ::rec_msg_and_serv::recResponse const> recResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rec_msg_and_serv::recResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rec_msg_and_serv::recResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rec_msg_and_serv

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/hydro/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/hydro/share/geometry_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/hydro/share/sensor_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rec_msg_and_serv::recResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rec_msg_and_serv::recResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rec_msg_and_serv::recResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rec_msg_and_serv::recResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rec_msg_and_serv::recResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rec_msg_and_serv::recResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rec_msg_and_serv::recResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b606c311d4979f1ba7567065c1c96178";
  }

  static const char* value(const ::rec_msg_and_serv::recResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb606c311d4979f1bULL;
  static const uint64_t static_value2 = 0xa7567065c1c96178ULL;
};

template<class ContainerAllocator>
struct DataType< ::rec_msg_and_serv::recResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rec_msg_and_serv/recResponse";
  }

  static const char* value(const ::rec_msg_and_serv::recResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rec_msg_and_serv::recResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/String[] models_found\n\
float32[] confidences_found\n\
geometry_msgs/Pose[] poses_found\n\
\n\
================================================================================\n\
MSG: std_msgs/String\n\
string data\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of postion and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
";
  }

  static const char* value(const ::rec_msg_and_serv::recResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rec_msg_and_serv::recResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.models_found);
      stream.next(m.confidences_found);
      stream.next(m.poses_found);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct recResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rec_msg_and_serv::recResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rec_msg_and_serv::recResponse_<ContainerAllocator>& v)
  {
    s << indent << "models_found[]" << std::endl;
    for (size_t i = 0; i < v.models_found.size(); ++i)
    {
      s << indent << "  models_found[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::std_msgs::String_<ContainerAllocator> >::stream(s, indent + "    ", v.models_found[i]);
    }
    s << indent << "confidences_found[]" << std::endl;
    for (size_t i = 0; i < v.confidences_found.size(); ++i)
    {
      s << indent << "  confidences_found[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.confidences_found[i]);
    }
    s << indent << "poses_found[]" << std::endl;
    for (size_t i = 0; i < v.poses_found.size(); ++i)
    {
      s << indent << "  poses_found[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "    ", v.poses_found[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // REC_MSG_AND_SERV_MESSAGE_RECRESPONSE_H
