(cl:defpackage soc_msg_and_serv-srv
  (:use )
  (:export
   "SEGMENT_AND_CLASSIFY"
   "<SEGMENT_AND_CLASSIFY-REQUEST>"
   "SEGMENT_AND_CLASSIFY-REQUEST"
   "<SEGMENT_AND_CLASSIFY-RESPONSE>"
   "SEGMENT_AND_CLASSIFY-RESPONSE"
  ))

